travis:
  secure:
    BINSTAR_TOKEN: T5T0fMjUsi9+PVu+scdaU940gTvXCJ/W1IuStl7Q8V6xKFvxW8/wXiKrPodUVoeGO2UrLl3uhXOxltwAdK5E/9P6EPnuYo1POBadbfxDOjYhcSyeHaz9E2mlchEmJ0Zt+T/9QXXYlk5h+lEzNuvr0V+f03PL0EYeWBiJy43SGlKI/Cq6maAEL0LgN0cAdCit5J/3Tscoucrf3yYnbOxIOzKzJtj3sT+kFjWfMchkfHUIlq0o0G28t96EV7cbm+VEn3TQaJxvOUE1LJ0Xziz5pcLSrHaDmmH/u70xOQ0zHJjj/cACjdgDISJgHAHghpZcHZxtxRHFmdjDzdKrM9F1WuGxhMJ6bAlFNvH4xRDvpoRBWHSypy5GLEKM5bVuOK9gMUfgHVes0EbcSpEPI3XJrOrZRJ16Utf2AQoTj44lXuJwJGEzkOP8NtwwFw6kuwLLiZn6hhLmRFjlxv8X+5NtnIpGjqnZttj5op0dffTZf8kYpiHoKNBgR2tnc1VDm6mMpkrvFemjLyUZAVRWZTGnJNE1FJRGSyzy3OSMsATkJdyUXlOoKSNwpkQFLBQPTULmZEA3djo21cdXKugMcju2nndGDvjlQMHE6rvsz4Vsx0yYhalHSvd8KZEZmGcVkj77+yMEXrhasTZY1Zy9zDxNQvIKsCKyk6FIsMfdwTBBbgg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
