appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: I1GRmrdk1J0okUvj7FHeuxbnZuBQOJED+OdRgtGB/4meVm6bIAr8I/ptPcGfDL46b9yV/zGXhbbynb3+9GP1TUnZOesmbPO/sFjTzx1h/4vNHb9l14vHoDaF0Hf8dlHrmrrPK4RyS3w4YzJZNNzRWaSOSRb138q1/VjwOiyHZycfFLjv5BXwwUZ2YFwvaBdd8UhA7R2ktjNzixWiOGPk2bwUcL7Dlj89F2IhqweYj/gdlKZKG6Bzuy+vtGX8n7pORd9UQ5GKXFkSMphpqgOFWTeQR40d9XIIcIOnHmCQYsc5z86AIrJhWddqIJhU1c8z57Gn0HpPHsZFhnYUHCkj1HOyx4PI9Gl+mxZQQcFw+C4Icka+kGEShtYej/TlFVVRUyogD4LtfFqWUl5FfjxnhNH4H0dG89anUwMo4cXluOsjmT+xCixiummkycXmckLz4btmYZLwc1lV8r3wmDMOgf04wYzQWTirK4RYCmYKSRo0hc2Qs160ZXL0wyfisZrOrWdnqfyg1uOjK6pMFV9x+SYWbPHDr3FcpnfmnQem9q/c2wNhV1IdLEM2FcRNh+3f3blm0WfZgQkJ5dEuq6IHFDxCUQTWppq6q8SSK97UVNz/PKlULSsy5QRXsWQa8DuJXcfYCQJ37AtUJqS6z3V2j1SAklVnoR/X9Ryee/t/cQI=}
